### ISSUE TITLE
Programme is not rebuilt

### ISSUE THREAD

**Issue by toster2015** [GoClipse/goclipse#178]
Hi, here is my problem. I installed golang and your plug-in for eclipse (goclipse), in short it is working great, but, when I am writing my code and running it some times it works great, but, after like 10 runs (the number seems random) any changes I made to the program have no effect, e.g. it is not being rebuilt (though the building process shows up in the console like normally). I tryed to manually remove the exe file from bin directory of my project, but found out some process is denying access to the file (I am on windows).

**Comment by bruno-medeiros** [comment]
Perhaps you launched your Go binary from Eclipse, it got stuck, and didn't terminate? When this happens, check the Debug view, and make sure all Eclipse launches are terminated.
Also what is the output of the Go build command when this issue occurs?

**Comment by urielhdz** [comment]
I 'm experiencing a similar problem, I'm starting with Go as a web server and each time I make a change I have to change the port in order to see my changes reflected, It seems that a rebuild does not stop the previos execution. 

The only way for me to unbind the previous executions of the script is by restarting Eclipse.

I'm on OS X 10.11.2 and installed Goclipse today.

**Comment by bruno-medeiros** [comment]
@urielhdz Like I said above, what is the output of the Go build command when this issue occurs? This can be seen in the `Go build` console. I can't figure out on my own what is happening on your computers.. :weary:

**Comment by urielhdz** [comment]
Here is the output :sob: 

************  Building Go project: hello  ************
  with GOPATH: /Users/$user/Documents/workspace/hello:/Users/$user/Documents/dev/go/packages
>> Running: /usr/local/go/bin/go install -v -gcflags "-N -l" main
   ^^^ Terminated, exit code: 0 ^^^
************  Build terminated.  ************

**Comment by bruno-medeiros** [comment]
@urielhdz that seems to indicate Go did not detect any changes in the Go source files. If it even tried to build package main, there should have been an output line with the text `main`, in that Go process output.
Are you sure all the Eclipse sources are saved? What happens if you try to invoke that command in a external command shell?

**Comment by bruno-medeiros** [comment]
closing as invalid
