### ISSUE TITLE
'Go to definition' does not work

### ISSUE THREAD

**Issue by abligh** [GoClipse/goclipse#185]
Selecting a method and using F3 / Go to definition does not always work. Here is a minimal program illustrating the point:

    package main
    
    import (
    	zmq "github.com/pebbe/zmq4"
    )
    
    func main() {
    	responder, _ := zmq.NewSocket(zmq.REP)
    	defer responder.Close()
    }

Put that in a new project, and pull zmq4 from github. Right click on 'NewSocket', 'REP' or 'Close' and do 'go to definition'. You will get the mysterious error *'selected position does not refer to a definition. Rather, it's a: selector'*. I am pretty sure this used to work.

**Comment by bruno-medeiros** [comment]
You sure this used to work? I can't compile that project due to a:
``` 
# github.com/pebbe/zmq4
github.com\pebbe\zmq4\errors.go:4:17: fatal error: zmq.h: No such file or directory
```
Usually if a project does compile due to import failures, then oracle doesn't work properly as well. (orace is the tool used to find def)

**Comment by abligh** [comment]
On 12 Feb 2016, at 12:35, Bruno Medeiros <notifications@github.com> wrote:

> You sure this used to work? I can't compile that project due to a:
> 
> # github.com/pebbe/zmq4
> github.com\pebbe\zmq4\errors.go:4:17: fatal error: zmq.h: No such file or directory
> 
> Usually if a project does compile due to import failures, then oracle doesn't work properly as well. (orace is the tool used to find def)

The project compiles fine here. You will have to install libzmq4 and its development headers to get that one to work.


-- 
Alex Bligh

**Comment by bruno-medeiros** [comment]
I'm on Windows, so I can't install that easily. In any case don't think it matters, this seem to be an oracle issue, same as this: https://github.com/GoClipse/goclipse/issues/176

Namely the problem is: https://github.com/golang/go/issues/13971

The good news is I might switch to using https://github.com/rogpeppe/godef instead, it seems nearly every other IDE/editor is using that, so it might have better support overall. And I did try it on the case above, and it seems to work.
