### ISSUE TITLE
Installing Goclipse of fresh Neon wants to use CDT 8.8 which causes dependency problems

### ISSUE THREAD

**Issue by mattfahrner** [GoClipse/goclipse#213]
I'm trying to install Goclipse on a fresh Eclipse Java EE instance for Mac and it wants to use CDT 8.8, which causes downstream update issues because Neon wants to use CDT 9.0. Goclipse documentation says it supports 9.0, but install dependencies seem to indicate otherwise. This screen is from a completely fresh install with Goclipse being the first add on:

![image](https://cloud.githubusercontent.com/assets/10586124/16543435/28a883f4-40a2-11e6-8a56-a2d54801e2a7.png)

Thanks in advance.

**Comment by aacebedo** [comment]
Same problem here !

**Comment by philrogers** [comment]
I get this when I attempted to install goclipse into Eclipse 
Eclipse IDE for C/C++ Developers

Version: Neon Release (4.6.0)
Build id: 20160613-1800

Cannot complete the install because of a conflicting dependency.
  Software being installed: GoClipse 0.16.0.v201606221240 (goclipse_feature.feature.group 0.16.0.v201606221240)
  Software currently installed: C/C++ Development Tools 9.0.0.201606062011 (org.eclipse.cdt.feature.group 9.0.0.201606062011)
  Only one of the following can be installed at once: 
    Eclipse C/C++ Development Tools 8.8.1.201602051005 (org.eclipse.cdt 8.8.1.201602051005)
    Eclipse C/C++ Development Tools 9.0.0.201606062011 (org.eclipse.cdt 9.0.0.201606062011)
  Cannot satisfy dependency:
    From: GoClipse 0.16.0.v201606221240 (goclipse_feature.feature.group 0.16.0.v201606221240)
    To: org.eclipse.cdt.platform.feature.group [8.8.0,9.0.0)
  Cannot satisfy dependency:
    From: C/C++ Development Tools 9.0.0.201606062011 (org.eclipse.cdt.feature.group 9.0.0.201606062011)
    To: org.eclipse.cdt.platform.feature.group [9.0.0.201606062011]
  Cannot satisfy dependency:
    From: C/C++ Development Platform 8.8.1.201602051005 (org.eclipse.cdt.platform.feature.group 8.8.1.201602051005)
    To: org.eclipse.cdt [8.8.1.201602051005]
  Cannot satisfy dependency:
    From: C/C++ Development Platform 9.0.0.201606062011 (org.eclipse.cdt.platform.feature.group 9.0.0.201606062011)
    To: org.eclipse.cdt [9.0.0.201606062011]

**Comment by bruno-medeiros** [comment]
The current documentation is incorrect, current Goclipse only supports 8.x CDT. This has already been fixed in master, I will make a release this week that supports CDT 9.0

**Comment by mattfahrner** [comment]
Many thanks - appreciate it!

**Comment by bruno-medeiros** [comment]
New release out.

**Comment by mattfahrner** [comment]
Thanks again for the quick update here!

**Comment by aacebedo** [comment]
That's working for me !
