### ISSUE TITLE
Error while installing guru.exe

### ISSUE THREAD

**Issue by venkysmv85** [GoClipse/goclipse#225]
Hi ,

Query 1:
When i go to eclipse --> window --> preferences --> guru --> Click Download.
It throws error:
![image](https://cloud.githubusercontent.com/assets/20844346/18254726/87573162-73be-11e6-8cff-c70efb9c13b7.png)
"go: missing Git command. See https://golang.org/s/gogetcmd
package golang.org/x/tools/cmd/guru: exec: "git": executable file not found in %PATH%"

I opened GIT Bash and run command : go get -u golang.org/x/tools/cmd/guru
Following is what i get:
![image](https://cloud.githubusercontent.com/assets/20844346/18254734/979cb0c4-73be-11e6-8745-5acade370936.png)

Query 2:
Request to verify my project directory:
![image](https://cloud.githubusercontent.com/assets/20844346/18254725/77fe6776-73be-11e6-893f-34f1ff85b1ff.png)

Even though the src or pkg is not present i could see .exe getting generated for my project.
Am i building the project correctly?

**Comment by bruno-medeiros** [comment]
Query 1:
You need git in your %PATH%. The GIT Bash probably adds the git path to %PATH% on it's own, but that only works for the Git Bash. Open the Windows shell (cmd.exe) and try to call git there. If it's not found, that's the problem, you need to add it to %PATH%, otherwise calling `go` from Eclipse won't find it either.

Query 2:
It is not necessary that a Go project has a `src` and `pkg` dir. The Eclispe project can also be located in the `src` dir of the GOPATH, which seems to be the case above. Seems like project Shiva is located inside `C:\Users\vsangepu\Documents\GoProjects\src`, and `C:\Users\vsangepu\Documents\GoProjects\` is the GOPATH
