### ISSUE TITLE
How to run a Unit Test for GO like Junit for JAVA

### ISSUE THREAD

**Issue by smfaizalkhan** [GoClipse/goclipse#248]
Before submitting an issue:

 *  Goclipse version.  0.16.1.v201607061938

     I wish to run a UNIT testing for GO code fom Eclipse.I have tried running the below methods

 1)Run ---> External Tool--->External Tool Configurations
          Created a new program  with below configurations

         1)Main tab the location is GO location
         2)Argument is test
         3)the working directory poiting to the eclipse workspace folder containing the package that           is to be tested

When i execute it it says "can't load package: package .: no buildable Go source files in /home/faizal/workspace/Sample"
 
 But i have the Go files in the folder 
 /home/faizal/workspace/Sample/src/main/goods_inspection.go
 
Please Let me what is the mistake am i doing ?

**Comment by bruno-medeiros** [comment]
Hum, it might be because you need to configure the GOPATH environment variable (in Environment tab).

The External Tool Configuration launches have no knowledge of Goclipse project configuration, so you will have to specify the same GOPATH environment variable as you have in the Goclipse/Go project.
